version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: flask --debug run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend/

  client:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend/
    links:
      - api
    depends_on:
      - api
