FROM python:3.9
WORKDIR /backend

# Copy the contents of the app to the Docker container
COPY backend/ .

# Install dependencies 
RUN pip install -r requirements.txt

EXPOSE 5001

# Flask entrypoint
ENTRYPOINT python main.py