services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    ports:
      - "5001:5001" 
  client:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - api