## STEP 1
FROM node:18-alpine as build_step
WORKDIR /frontend

COPY frontend/ .

RUN npm install react-scripts@5.0.1 -g --silent

EXPOSE 3000

# start app
CMD ["npm", "run", "build"]


## STEP 2
FROM nginx:stable-alpine

# Copy contents of npm build to container
COPY --from=build-step /frontend/build /usr/share/nginx/html

# Copy NGINX config to container
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf